markdown: rdiscount
highlighter: pygments
baseurl: /
staticurl: /static/

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    permalink: /projekte/:path/


permalink: blog/:year/:month/:title/
paginate: 8
paginate_path: blog/page/:num/

sass:
  style: compressed
